n = int(input())
n_nums = set(int(inputStr) for inputStr in input().split())
n_nums = list(n_nums)
n_nums.sort()
n_nums = set(n_nums)
m = int(input())
m_nums = set(int(inputStr) for inputStr in input().split())
m_nums = list(m_nums)
m_nums.sort()
m_nums = set(m_nums)
difference = list(n_nums.difference(m_nums))
for i in m_nums.difference(n_nums):
    difference.append(i)
difference.sort()
for i in difference:
    print(i)
